local Fluent=loadstring(game:HttpGet("https://raw.githubusercontent.com/taithedev/SmoothFluent/main/src/Fluent.lua"))()
local Window=Fluent:CreateWindow({Title="SmoothFluent",SubTitle="Modern Roblox UI",Size=UDim2.fromOffset(650,500),Search=true})
local Main=Window:AddTab({Title="Main"})
local Controls=Main:AddSection("Controls")
Controls:AddButton({Title="Test notification",Description="Check callbacks and notifications.",Callback=function() Fluent:Notify({Title="SmoothFluent",Content="It works.",Type="Success"}) end})
Controls:AddToggle("Enabled",{Title="Enabled",Default=true,Callback=function(v) print("Enabled:",v) end})
Controls:AddSlider("Power",{Title="Power",Min=0,Max=100,Default=50,Callback=function(v) print("Power:",v) end})
Controls:AddDropdown("Mode",{Title="Mode",Values={"Normal","Advanced","Performance"},Default="Normal",Callback=function(v) print("Mode:",v) end})
local Settings=Window:AddTab({Title="Settings"})
Settings:AddSection("Interface"):AddButton({Title="AMOLED theme",Callback=function() Fluent:SetTheme("AMOLED") end})
